# Generated by Django 2.2.6 on 2022-02-10 22:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0002_bmi'),
    ]

    operations = [
        migrations.AddField(
            model_name='bmi',
            name='text',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
