# Generated by Django 2.2.6 on 2022-02-10 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0003_bmi_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BMI',
        ),
    ]
